/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.net.Socket;
import java.util.*;
import java.util.ArrayList;
import javax.swing.JList;
/**
 *
 * @author yuchiang
 */
public class MessagerGUI extends javax.swing.JFrame {
    static User user;
    static Socket socket;
    /**
     * Creates new form MessagerGUI
     */
    private HashMap<String , SingleChat> chatMap;
    public MessagerGUI(Curinfo c,User user,Socket socket) {
        initComponents(c);
        this.socket = socket;
        this.user = user;
        chatMap = new HashMap<String , SingleChat>();
    }

    
    // public ArrayList<String> setOfflineList(ArrayList<String> curoffline){
    //     offlineList = new Jlist<String>(curoffline.toArray());
    // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Curinfo c) {

        jScrollPane1 = new javax.swing.JScrollPane();
       // onlineList = new javax.swing.JList(c.curonline.toArray());
        chatroomButton = new javax.swing.JButton();
        onlineButton = new javax.swing.JButton();
        onlineLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList(c.curonline.toArray());
        offlineList = new javax.swing.JList(c.curoffline.toArray());
        offlineLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatroomHistoryList = new javax.swing.JList<>();
        chatroomHistoryLabel = new javax.swing.JLabel();
        offlineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Messenger");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        onlineList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        onlineList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                onlineListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(onlineList);

        chatroomButton.setText("Invite friends");
        chatroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatroomButtonActionPerformed(evt);
            }
        });

        onlineButton.setText("Start to talk");
        onlineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineButtonActionPerformed(evt);
            }
        });

        onlineLabel.setText("Online");

        jScrollPane2.setViewportView(offlineList);

        offlineLabel.setText("Offline");
        chatroomHistoryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(chatroomHistoryList);

        chatroomHistoryLabel.setText("Chatroom history");

        offlineButton.setText("Offline Message");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onlineButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(offlineLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1))
                    .addComponent(onlineLabel)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chatroomButton)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chatroomHistoryLabel)
                    .addComponent(offlineButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatroomHistoryLabel)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatroomButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onlineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(offlineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(offlineButton))
        );

        pack();
    }// </editor-fold>             

    private void chatroomButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        // TODO add your handling code here:
        FriendSelection f = new FriendSelection();
        f.setVisible(true);
    }                                              

    private void onlineButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        
        // TODO add your handling code here:
        // if (evt.getValueIsAdjusting() == false) {
            if (onlineList.getSelectedIndex() == -1) {
            //No selection, disable fire button.
                onlineButton.setEnabled(false);
            } else {
            //Selection, enable the fire button.
                onlineButton.setEnabled(true);
            }
        // }
        SingleChat s = new SingleChat(this.user,socket);
        s.setTitle(onlineList.getSelectedValue());
        chatMap.put(onlineList.getSelectedValue(), s);
        s.setVisible(true);
    }                                               
    public void getMessage(String username,String msg){
        SingleChat temp_chat = new SingleChat(null,null);
        temp_chat = chatMap.get(username);
        temp_chat.addMessageToScreen(username,msg);
    }

    private void onlineListValueChanged(javax.swing.event.ListSelectionEvent evt) {                                        
        // TODO add your handling code here:
        if (onlineList.getSelectedIndex() == -1) {
        //No selection, disable fire button.
            onlineButton.setEnabled(false);
        } else {
        //Selection, enable the fire button.
            onlineButton.setEnabled(true);
        }
        
    }    
    public void updateList(Curinfo c){
        onlineList = new javax.swing.JList(c.curonline.toArray());
        offlineList = new javax.swing.JList(c.curoffline.toArray());
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         new MessagerGUI(c).setVisible(true);
        //     }
        // });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton chatroomButton;
    private javax.swing.JLabel chatroomHistoryLabel;
    private javax.swing.JList<String> chatroomHistoryList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton offlineButton;
    private javax.swing.JLabel offlineLabel;
    private javax.swing.JList<String> offlineList;
    private javax.swing.JButton onlineButton;
    private javax.swing.JLabel onlineLabel;
    private javax.swing.JList<String> onlineList;
    // End of variables declaration                   
}